### ISSUE TITLE
beats per minute count is not correct

### ISSUE THREAD

**Issue by guitarrista** [ElJere/aCompas#8]
Could you check the bpm count? Right now it shows a number which is 2/3 of the pulses/counts per minute. So when it displays 120 bpm, it is actually 180 pulses/counts per minute (in this convention a count/pulse is what one bulerias compas has 12 of, for example - to give you an idea of what i am referring to). This is regardless of what palo it is. 

So it seems it neither shows a number of counts, nor a number of beats (accented pulses), per minute. I think conventionally it would be nice to show the counts/pulses per minute, in which case you would multiply what you display now by 3/2 (i.e. by 1.5).
Thank you for your consideration.

**Comment by ghost** [comment]
Ok, I'll investigate on this. It seems there is indeed an issue with the bpm count (maybe not exactly the one you mention, but still : there is a problem) and thanks for reporting it.

**Comment by ghost** [comment]
Here are the results of my investigations. According to me the BPM value for binary rhythms (rumba and tangos) was fine. But there was indeed a bug regarding the BPM value for other rhythms. The number which was displayed was twice what it should be.

Important remark : the flamenco metronomes I know take the eighth-note as a reference for the BPM, which I disagree with. A Compás takes the quarter-note as a reference for the BPM, like most (if not all) non-flamenco metronomes do.
An interesting reading : https://en.wikipedia.org/wiki/Tempo#Beats_per_minute

There is no totally right or wrong way, there are just several ways of doing things (in our case, several possible note length to consider for choosing a reference for the BPM). I decided to keep the quarter-note as a reference and not the eighth-note because most of the metronomes / beat machines count that way.

I tested the BPM value with a good old physical metronome and everything looks / sounds ok to me now.

A big thanks for your bug report, @guitarrista .

**Comment by ghost** [comment]
P.S. : The website is already contains my fix. I also pushed a new version of the Android application on Google Play, which will be available within 24h (Google does not push releases on the devices instantaneously and there are a few hours to wait before new versions get propagated).

**Comment by guitarrista** [comment]
thank you very much! great work!!

**Comment by jboe67** [comment]
The problem is definitely NOT solved, neither on the website nor in the Android app. For example if you choose the Soleá compás: To get an output of 60 bpm you have to set the application on 20 bpm (may be approximately). Apart from that bug the application seems very useful and well elaborated ;-)
